### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dnlup** [therealklanni/jp#2]
@therealklanni 
Hi, thanks for this package.

I tried to run version v2.0.1 and v2.0.0 and get the following error:
```
/usr/bin/jp: line 1: syntax error near unexpected token `('
/usr/bin/jp: line 1: `const _ = require(`lodash`)'
```

I think the problem is that  
```
#!/usr/bin/env node
```

is missing at the beginning of the `index.js` file. Would have submitted a PR but I don' know how you would like to proceed beause I saw that in older versions you kept different files for the commandline file and the `index.js`  file.

My node version is 6.10.3.
My npm version is 3.10.10.

**Comment by therealklanni** [comment]
Ah, you're right. Thanks for the info! I need to start using `npm pack` to test the installed binary. I'll publish a fix soon.

**Comment by therealklanni** [comment]
jp-cli 2.0.2 published 🎉

**Comment by dnlup** [comment]
Thanks!
